import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static java.time.Clock.system;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JToggleButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alaa.Ezzeldin
 */

public class MemoryAllocation extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */   
    public MemoryAllocation() {
        initComponents();
        getContentPane().setBackground(Color.black); 
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           
    
    int MemorySize;
    ArrayList < MemoryLocation> hole = new ArrayList < >() ;
    int i=1;
    MemoryLocation Process=  new MemoryLocation();
    ArrayList<MemoryLocation> cells1 = new ArrayList< > ();
    ArrayList<MemoryLocation> cells = new ArrayList< > ();
    int FirstTime=0;
    boolean selected = false;
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jFrame6 = new javax.swing.JFrame();
        panel1 = new java.awt.Panel();
        ProcessSizeSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        AddHole = new javax.swing.JButton();
        StartHoleSpinner = new javax.swing.JSpinner();
        HoleSizespinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddProcess = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Holelist = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        processlist = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        NoOfHolesSpinner = new javax.swing.JSpinner();
        panel2 = new java.awt.Panel();
        AllocateButton = new javax.swing.JButton();
        MemorySizeSpinner = new javax.swing.JSpinner();
        MemoryPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DeallocateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MethodUsedChoice = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame6Layout.setVerticalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 0, 51));
        panel1.setForeground(new java.awt.Color(0, 255, 204));

        ProcessSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Size of Process");

        AddHole.setBackground(new java.awt.Color(0, 0, 0));
        AddHole.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddHole.setForeground(new java.awt.Color(51, 153, 255));
        AddHole.setText("ADD");
        AddHole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddHole(evt);
            }
        });

        StartHoleSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        HoleSizespinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Hole size");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Starting Address");

        AddProcess.setBackground(new java.awt.Color(0, 0, 0));
        AddProcess.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddProcess.setForeground(new java.awt.Color(51, 153, 255));
        AddProcess.setText("ADD");
        AddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProcess(evt);
            }
        });

        jScrollPane1.setViewportView(Holelist);

        jScrollPane2.setViewportView(processlist);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("No. of Holes");

        NoOfHolesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        NoOfHolesSpinner.setName(""); // NOI18N
        NoOfHolesSpinner.setValue(1);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddHole, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NoOfHolesSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(HoleSizespinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(StartHoleSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addGap(207, 207, 207)
                                            .addComponent(ProcessSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ProcessSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(AddProcess)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NoOfHolesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(HoleSizespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(StartHoleSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddHole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        StartHoleSpinner.getAccessibleContext().setAccessibleName("");

        panel2.setBackground(new java.awt.Color(0, 0, 51));

        AllocateButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        AllocateButton.setForeground(new java.awt.Color(51, 153, 255));
        AllocateButton.setText("Allocate");
        AllocateButton.setActionCommand("");
        AllocateButton.setEnabled(false);
        AllocateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllocateButtonActionPerformed(evt);
            }
        });

        MemorySizeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        MemoryPanel.setOpaque(false);

        javax.swing.GroupLayout MemoryPanelLayout = new javax.swing.GroupLayout(MemoryPanel);
        MemoryPanel.setLayout(MemoryPanelLayout);
        MemoryPanelLayout.setHorizontalGroup(
            MemoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        MemoryPanelLayout.setVerticalGroup(
            MemoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("Memory Size");

        DeallocateBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DeallocateBtn.setForeground(new java.awt.Color(51, 153, 255));
        DeallocateBtn.setText("Deallocate");
        DeallocateBtn.setEnabled(false);
        DeallocateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeallocateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(MemorySizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AllocateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeallocateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(MemoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(MemorySizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(AllocateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(DeallocateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MemoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Memory Allocation");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Method used");

        MethodUsedChoice.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        MethodUsedChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Fit", "Best Fit" }));
        MethodUsedChoice.setBorder(null);
        MethodUsedChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodUsedChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MethodUsedChoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(MethodUsedChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("Method");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void MethodUsedChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodUsedChoiceActionPerformed
       
    }//GEN-LAST:event_MethodUsedChoiceActionPerformed
    
    private void AddHole(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddHole
        // TODO add your handling code here
        
        MemoryLocation x= new MemoryLocation();
        x.setID(0);
        x.setType("Hole");
        x.setSize((int)HoleSizespinner.getValue());
        x.setStartTime ((int)StartHoleSpinner.getValue());
        
        Holelist.setModel(new DefaultListModel());
    
        hole.add(x);
        
        DefaultListModel<String> HoleListModel = (DefaultListModel) Holelist.getModel();
        HoleListModel.addElement(x.getDescripton());
        
            if ((int) HoleSizespinner.getValue() <= Holelist.getModel().getSize()) {            
            AddHole.setEnabled(false);
        }
                  
//        DefaultListModel<String> holeListModel;
//        try{
//            holeListModel= (DefaultListModel) Holelist.getModel();
//        }catch(Exception ex){
//            Holelist.setModel(new DefaultListModel());        
//        }
//        holeListModel = (DefaultListModel) Holelist.getModel();
//        
//        holeListModel.addElement(x.getDescripton());
//        Holelist.setModel(holeListModel);
//        //IDSpinner.setValue(((int) IDSpinner.getValue()) + 1);
//        if ((int) NoOfHolesSpinner.getValue() <= Holelist.getModel().getSize()) {
//            AddHole.setEnabled(false);
//        }
  
        
    }//GEN-LAST:event_AddHole

    private void AddProcess(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProcess
        // TODO add your handling code here:
        MemoryLocation x= new MemoryLocation();
        x.setID(i++);
        x.setType("Process");
        x.setSize((int)ProcessSizeSpinner.getValue());
        x.setStartTime(0);
        
        Process= x;

        processlist.setModel(new DefaultListModel());

        DefaultListModel<String> processListModel = (DefaultListModel) processlist.getModel();
        processListModel.addElement(x.getDescripton());
        AllocateButton.setEnabled(true);
    }//GEN-LAST:event_AddProcess

    private void AllocateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllocateButtonActionPerformed
        // TODO add your handling code here:
        
        MemorySize=(int)MemorySizeSpinner.getValue();
        
        MemoryPanel.removeAll();
        
        if(MethodUsedChoice.getSelectedItem() == "First Fit"){
            MemoryLocation AlgorithmFF = new MemoryLocation();
            MemorySize=(int)MemorySizeSpinner.getValue();
            if(FirstTime==0){
                cells1 = AlgorithmFF.update(hole, MemorySize);
                cells = AlgorithmFF.FirstFit(Process, cells1);
            }
            else{
              cells = AlgorithmFF.FirstFit(Process, hole);
            }
        }

        if (MethodUsedChoice.getSelectedItem() == "Best Fit"){
            MemoryLocation AlgorithmBF = new MemoryLocation();
            MemorySize=(int)MemorySizeSpinner.getValue();
            if(FirstTime==0){
                cells1 = AlgorithmBF.update(hole, MemorySize);
                cells = AlgorithmBF.BestFit(Process, cells1);
            }
            else{
                cells = AlgorithmBF.BestFit(Process, hole);
            }
        }
        
        MemoryPanel.setLayout(new BoxLayout(MemoryPanel, BoxLayout.Y_AXIS));
        
        MemoryLocation Deallocate = new MemoryLocation();

        for (int i = 0; i < cells.size(); i++) {
            if(cells.get(i).getType()=="Used")
            {
                String s =cells.get(i).getType()+"  "+"Size:"+cells.get(i).getsize();
                JButton btn = new JButton(s);
                btn.setAlignmentX(CENTER_ALIGNMENT);
                btn.setBackground(Color.lightGray);
                btn.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));
                if(selected ==false){
                btn.addMouseListener(new MouseAdapter() { 
                        public void mouseClicked(MouseEvent me) { 
                                btn.setBackground(Color.red);                                       
                                DeallocateBtn.setEnabled(true);
                                selected = true;
                        } 
                    });
                }
                MemoryPanel.add(btn);
            }

            else if(cells.get(i).getType()=="Hole")
                {
                    String s = cells.get(i).getType()+"   "+"Size:"+cells.get(i).getsize();
                    JButton btn = new JButton(s);

                    btn.setAlignmentX(CENTER_ALIGNMENT);

                    btn.setBackground(Color.white);
                    btn.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));
                    MemoryPanel.add(btn);
                }


             else if (cells.get(i).getType()=="Process")
                {
                    String s ="  P"+cells.get(i).getID()+"   "+"Size:"+cells.get(i).getsize();
                    JButton btn = new JButton(s);    

                    btn.setAlignmentX(CENTER_ALIGNMENT);

                    btn.setBackground(Color.pink);
                    btn.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));
                    MemoryPanel.add(btn);
                    if(selected ==false){
                    btn.addMouseListener(new MouseAdapter() { 
                            public void mouseClicked(MouseEvent me) { 
                                    btn.setBackground(Color.red);
                                    selected = true;
                                    DeallocateBtn.setEnabled(true);
                            } 
                        });
                    }
                    MemoryPanel.add(btn);
                }
            
             }            

        hole= (ArrayList<MemoryLocation>) cells.clone();
        hole.clear();

            
        for(int i=0; i<cells.size();i++){
            hole.add(cells.get(i));
        } 
                    
        MemoryPanel.setVisible(true);
        MemoryPanel.validate();
        MemoryPanel.repaint();

        FirstTime++;
        Process= new MemoryLocation();

        AllocateButton.setEnabled(false);
    }//GEN-LAST:event_AllocateButtonActionPerformed

    private void DeallocateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeallocateBtnActionPerformed
//        // TODO add your handling code here: 
    if(selected == true){
      //  DeallocateBtn.setEnabled(true); 
      selected =false;
        MemoryLocation DeLoc = new MemoryLocation();
        
        for(int i=0; i<MemoryPanel.getComponentCount();i++){
            if(MemoryPanel.getComponent(i).getBackground()==Color.red){
                DeLoc= hole.get(i);
            }
        }
        MemoryPanel.removeAll();

        MemoryLocation Deallocate = new MemoryLocation();
        cells = Deallocate.Deallocate(hole,DeLoc);
        
        MemoryPanel.setLayout(new BoxLayout(MemoryPanel, BoxLayout.Y_AXIS));        
        
        for (int i = 0; i < cells.size(); i++) {
                    if(cells.get(i).getType()=="Used")
                    {
                        String s =cells.get(i).getType()+"  "+"Size:"+cells.get(i).getsize();
                        JButton btn = new JButton(s);
                        btn.setAlignmentX(CENTER_ALIGNMENT);
                        btn.setBackground(Color.lightGray);
                        
                        btn.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));
                        
                        if(selected ==false){
                        btn.addMouseListener(new MouseAdapter() { 
                                public void mouseClicked(MouseEvent me) { 
                                        btn.setBackground(Color.red);
                                        selected = true;
                                        DeallocateBtn.setEnabled(true);
                                } 
                            });
                        }
                        MemoryPanel.add(btn);
                        
                                                
                        cells.get(i).setEndTime();
                        String c =cells.get(i).getStartTime()+" ";
                        JLabel lbl = new JLabel(c);
                        lbl.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));

                        lbl.setAlignmentY(LEFT_ALIGNMENT);
                        lbl.setAlignmentX(BOTTOM_ALIGNMENT);
                        
                        lbl.setFont(new Font("Serif", Font.BOLD, 16));
                        lbl.setForeground(Color.blue);
                                                
                    }

                    else if(cells.get(i).getType()=="Hole")
                        {
                            String s = cells.get(i).getType()+"   "+"Size:"+cells.get(i).getsize();
                            JButton btn = new JButton(s);

                             btn.setAlignmentX(CENTER_ALIGNMENT);
                     
                            btn.setBackground(Color.white);
                            btn.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));
                            MemoryPanel.add(btn);
                            
                        cells.get(i).setEndTime();
                        String c =cells.get(i).getStartTime()+" ";
                        JLabel lbl = new JLabel(c);
                        lbl.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));

                        lbl.setAlignmentY(LEFT_ALIGNMENT);
                        lbl.setAlignmentX(BOTTOM_ALIGNMENT);
                        
                        lbl.setFont(new Font("Serif", Font.BOLD, 16));
                        lbl.setForeground(Color.blue);
                        }


                     else if (cells.get(i).getType()=="Process")
                        {
                            String s = "  P"+cells.get(i).getID()+"   "+"Size:"+cells.get(i).getsize();
                            JButton btn = new JButton(s);    
                            
                            btn.setAlignmentX(CENTER_ALIGNMENT);
                        
                            btn.setBackground(Color.pink);
                            btn.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));
                            MemoryPanel.add(btn);
                            
                            if(selected ==false){
                            btn.addMouseListener(new MouseAdapter() { 
                                    public void mouseClicked(MouseEvent me) { 
                                            btn.setBackground(Color.red);
                                            selected = true;
                                            DeallocateBtn.setEnabled(true);
                                    } 
                                });
                            }

                        cells.get(i).setEndTime();
                        String c =cells.get(i).getStartTime()+" ";
                        JLabel lbl = new JLabel(c);
                        lbl.setPreferredSize(new Dimension(100,cells.get(i).getsize()* 20 ));

                        lbl.setAlignmentY(LEFT_ALIGNMENT);
                        lbl.setAlignmentX(BOTTOM_ALIGNMENT);
                        
                        lbl.setFont(new Font("Serif", Font.BOLD, 16));
                        lbl.setForeground(Color.blue);
                        }
            
             }            
        
            hole= (ArrayList<MemoryLocation>) cells.clone();
            hole.clear();

            for(int i=0; i<cells.size();i++){
                hole.add(cells.get(i));
            } 
    }                
            MemoryPanel.setVisible(true);
            MemoryPanel.validate();
            MemoryPanel.repaint();
            
            FirstTime++;
            Process= new MemoryLocation();
            selected = false;
            DeallocateBtn.setEnabled(false);

            
            
    }//GEN-LAST:event_DeallocateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MemoryAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MemoryAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MemoryAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MemoryAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryAllocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddHole;
    private javax.swing.JButton AddProcess;
    private javax.swing.JButton AllocateButton;
    private javax.swing.JButton DeallocateBtn;
    private javax.swing.JSpinner HoleSizespinner;
    private javax.swing.JList<String> Holelist;
    private javax.swing.JPanel MemoryPanel;
    private javax.swing.JSpinner MemorySizeSpinner;
    private javax.swing.JComboBox<String> MethodUsedChoice;
    private javax.swing.JSpinner NoOfHolesSpinner;
    private javax.swing.JSpinner ProcessSizeSpinner;
    private javax.swing.JSpinner StartHoleSpinner;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JList<String> processlist;
    // End of variables declaration//GEN-END:variables


}
